name: E2E tests

on:
  push:
  pull_request:
    types: [opened,reopened,synchronize]

jobs:

  e2e_tests:
    runs-on: ubuntu-latest
    name: E2E tests

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Running latest prestashop with docker
        run: docker-compose up --build -d

      - name: Wait for prestashop to be ready
        uses: juliangruber/sleep-action@v1
        with:
          time: 45s

      - name: Run tests
        run: |
          npm install && npm run e2e-tests
        env:
          URL_FO: http://localhost/
          HEADLESS: true
          PS_VERSION: "1.7.7"
        working-directory: ./tests/E2E
