name: PHP tests
on: [push, pull_request]

jobs:
  php-linter:
    name: PHP Syntax check 7.4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@master

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: PrestaShop/.github/.github/actions/php-ci/php-cs@master
        with:
          php-version: '7.4'

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presta-version: [ '1.7.7.x', '1.7.8.x', '8.2.x']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      
      - uses: PrestaShop/.github/.github/actions/php-ci/phpstan@master
        with:
          php-version: '7.4'
          presta-version: ${{ matrix.presta-version }}
          module-name: ${{ github.event.repository.name }}
          phpstan-level: '5'
          phpstan-config: 'tests/phpstan/phpstan-${{ matrix.presta-version }}.neon'
          phpstan-version: '^0.12'
          composer-version: '2.2.18'